// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqtphbwwlejeqmhtzonp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxdHBoYnd3bGVqZXFtaHR6b25wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MDU2MjksImV4cCI6MjA1ODE4MTYyOX0.BJRul7ACxHAvBkUzB5PScJ-Mg5HwHgjP-wogCKQVh4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);